### ISSUE TITLE
Cosmos DB int tests failing on main branch

### ISSUE THREAD

**Issue by Izzzu** [eclipse-dataspaceconnector/DataSpaceConnector#1057]
# Bug Report

## Describe the Bug

Cosmos DB integration tests are failing on main branch.

### Expected Behavior

Tests should be passing on main branch.

### Observed Behavior

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5793633945?check_suite_focus=true

## Steps to Reproduce
Steps to reproduce the behavior locally:
1. Set the COSMOS_URL env var to empty string and COSMOS_KEY to some value.
2. Run Cosmos DB int test
3. The stacktrace should be the same as the one in the build logs linked above: 

```
java.lang.NullPointerException
        at com.azure.cosmos.implementation.routing.LocationHelper.getLocationEndpoint(LocationHelper.java:28)
        at com.azure.cosmos.CosmosClientBuilder.lambda$validateConfig$0(CosmosClientBuilder.java:825)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.azure.cosmos.CosmosClientBuilder.validateConfig(CosmosClientBuilder.java:821)
        at com.azure.cosmos.CosmosClientBuilder.buildClient(CosmosClientBuilder.java:783)
        at org.eclipse.dataspaceconnector.azure.testfixtures.CosmosTestClient.azureClient(CosmosTestClient.java:44)
        at org.eclipse.dataspaceconnector.azure.testfixtures.CosmosTestClient.createClient(CosmosTestClient.java:33)
        at org.eclipse.dataspaceconnector.assetindex.azure.CosmosAssetIndexIntegrationTest.prepareCosmosClient(CosmosAssetIndexIntegrationTest.java:63)
```
 
## Context Information

The tests started failing after merging the PR about not using Cosmos DB but cloud resources [PR #170]( https://github.com/agera-edc/DataSpaceConnector/issues/170).
The way how it works now is:
If COMSOS_KEY env var is set then the test will be executed. Additionally there’s COSMOS_URL env var which is set by default to https://cosmos-itest.documents.azure.com/  if no value is provided.

## Possible Implementation

The potential reason for this issue is that the COSMOS_URL env is set in EDC repo but it's empty.

Possible solutions:
1. Remove the COSMOS_URL env variable from EDC repository
2. Set the correct COSMOS_URL env variable in EDC repository
3. Use default value in the code when the env value us null **or blank**: 
```java
public class ConfigurationFunctions {

    /**
     * Returns the property value, env value or default value for the key.
     * <p>Naming conventions for keys are '[qualifier].[value]' in lower case. When checking for env variables, keys will be converted to uppercase and '.' replaced by '_'.</p>
     */
    public static String propOrEnv(String key, String defaultValue) {
        String value = System.getProperty(key);
        if (value != null) {
            return value;
        }
        String upperKey = key.toUpperCase().replace('.', '_');
        value = System.getenv(upperKey);
        return value != null ? value : defaultValue;
    }

}
```

**Comment by Izzzu** [comment]
PR #1064 didn't solve this
