### ISSUE TITLE
EdcRuntimeExtension: Can't load injected implementations when working with SQL Policy Store

### ISSUE THREAD

**Issue by SmartUtkarsh** [eclipse-dataspaceconnector/DataSpaceConnector#1135]
# Bug Report

## Describe the Bug
_When trying the to implement sql policy store implementation. The EdcInjectionException is thrown for contractDefinitionStore and sqlPolicyStore even after providing appropriate dependencies_

### Expected Behavior
_The build should get succeed and the the application should run with SqlPolicyStore_

### Observed Behavior
_When adding `:extensions:sql:policy:store` and `:extensions:sql:contract-definition:store` the shadowJar is not created properly. After checking the generated jar I noticed the contract definition classes are not being picked up_

## Steps to Reproduce
We are trying EDC with following dependency structure.
1. Create the module using following gradle file
```

plugins {
    `java-library`
    id("application")
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

val rsApi: String by project

dependencies {
    implementation(project(":extensions:dataloading"))
    implementation(project(":extensions:api:api-core"))
    implementation(project(":extensions:sql:policy:store"))
    implementation(project(":extensions:sql"))
    implementation(project(":extensions:sql:asset:index"))
    implementation(project(":extensions:sql:pool:apache-commons-pool"))
//    implementation(project(":extensions:sql:contract-definition:store")) // Since this dependency is part of extensions:sql not needed again
    implementation(project(":extensions:aws"))
    implementation(project(":extensions:transaction:transaction-local"))
    implementation(project(":extensions:api:data-management:asset"))
    implementation(project(":common:util"))
    implementation(project(":data-protocols:ids"))
    implementation(project(":extensions:iam:iam-mock"))
    implementation(project(":extensions:data-plane:data-plane-http"))
    implementation(project(":extensions:data-plane:data-plane-framework"))
    implementation(project(":extensions:data-plane:data-plane-spi"))
    implementation("org.postgresql:postgresql:42.3.3")
    implementation("jakarta.ws.rs:jakarta.ws.rs-api:${rsApi}")
}


application {
    mainClass.set("org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime")
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    exclude("**/pom.properties", "**/pom.xm")
    mergeServiceFiles()
    archiveFileName.set("provider.jar")
}
```
2. Aim is to use following class with other mentioned classes.
```
 @Inject
 SqlPolicyStore sqlPolicyStore;
```
3. Build gets successful on invoking
```
./gradlew clean samples:sql-policy-demo:provider:build
```
4. When we run the generated Uber/Fat jar with following command, It gives following error
```
 java -Dedc.fs.config=samples/sql-policy-demo/provider/config.properties -jar samples/sql-policy-demo/provider/build/libs/provider.jar
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

INFO 2022-04-12T22:17:40.723493 Initialized Null Vault
SEVERE 2022-04-12T22:17:40.794663 Error booting runtime
org.eclipse.dataspaceconnector.spi.system.injection.EdcInjectionException: The following injected fields were not provided:
Field "contractDefinitionStore" of type [interface org.eclipse.dataspaceconnector.spi.contract.offer.store.ContractDefinitionStore] required by org.eclipse.dataspaceconnector.contract.ContractServiceExtension
Field "sqlPolicyStore" of type [class org.eclipse.dataspaceconnector.sql.policy.store.SqlPolicyStore] required by org.eclipse.dataspaceconnector.extensions.api.ProviderExtension
Field "contractDefinitionStore" of type [interface org.eclipse.dataspaceconnector.spi.contract.offer.store.ContractDefinitionStore] required by org.eclipse.dataspaceconnector.extensions.api.ProviderExtension
	at org.eclipse.dataspaceconnector.boot.system.ExtensionLoader.sortExtensions(ExtensionLoader.java:194)
	at org.eclipse.dataspaceconnector.boot.system.ExtensionLoader.loadServiceExtensions(ExtensionLoader.java:149)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:183)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:106)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:90)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:69)

```

## Context Information
_It seems dependency issues. The generated Jar does not contain the contract definition store class. Upon adding the classes manually as library the example is working_

- Used version: EDC v1.0.0
- OS:ubuntu

## Detailed Description
_Provided above_

## Possible Implementation
_Seems the dependency is not being loaded in the generated jar_

**Comment by ndr-brt** [comment]
Thanks for reporting.
After a sneak peek:
- on the point `2.`, you can't inject the `SqlPolicyStore` implementation, you should inject the interface `PolicyStore`
- what if you uncomment the `implementation(project(":extensions:sql:contract-definition:store"))` row? it works?

**Comment by SmartUtkarsh** [comment]
Thanks for replying back @ndr-brt 
Thanks for highlighting, Changed to PolicyStore Spi now. 

But the error remains for `contractDefinitionStore` dependency as follow after uncommenting the dependency `implementation(project(":extensions:sql:contract-definition:store"))`
```
org.eclipse.dataspaceconnector.spi.system.injection.EdcInjectionException: The following injected fields were not provided:
Field "contractDefinitionStore" of type [interface org.eclipse.dataspaceconnector.spi.contract.offer.store.ContractDefinitionStore] required by org.eclipse.dataspaceconnector.contract.ContractServiceExtension
Field "contractDefinitionStore" of type [interface org.eclipse.dataspaceconnector.spi.contract.offer.store.ContractDefinitionStore] required by org.eclipse.dataspaceconnector.extensions.api.ProviderExtension
	at org.eclipse.dataspaceconnector.boot.system.ExtensionLoader.sortExtensions(ExtensionLoader.java:194)
	at org.eclipse.dataspaceconnector.boot.system.ExtensionLoader.loadServiceExtensions(ExtensionLoader.java:149)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:183)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:106)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:90)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:69)
Disconnected from the target VM, address: '127.0.0.1:47105', transport: 'socket'
```

**Comment by ndr-brt** [comment]
I think it's an issue with gradle: https://github.com/gradle/gradle/issues/847
Probably we would need to give unique names to the modules

**Comment by SmartUtkarsh** [comment]
Thanks for the quick response and identifying the issue. Can we expect the fix having unique module name soon?

**Comment by ndr-brt** [comment]
Opened a PR about this, would you be so kind to have a try on that commit? (module names are changed, details in the PR #1154 )

**Comment by SmartUtkarsh** [comment]
Thanks for helping out, @ndr-brt . I have verified the PR and code works fine :+1:

**Comment by ndr-brt** [comment]
Good! Let's keep this open until the PR gets merged
