### ISSUE TITLE
DataManagementAPI - ContractNegotiationApiController : Initiate ContractNegotiation by PolicyId not working

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1251]
# Bug Report

## Describe the Bug

At the time of writing contract negotiation can be initiated by sending a `NegotiationInitiateRequestDto` to the data management API. This object contains a `ContractOfferDescription` which looks something like this

```java
public class ContractOfferDescription {
    @NotNull
    private final String offerId;
    @NotNull
    private final String assetId;
    private final String policyId;
    private final Policy policy;
}
```

In this class ether the `policy` or the `policyId` must be set for the description to be valid. In case the call is done using the `policyId` the connector is logging the following message (in a very high frequency):

```bash
[2022-05-03 14:05:19] [FINE   ] [Consumer] Failed to send contract offer with id 1:foo. ContractNegotiation 1a793260-aefc-47b8-ae22-408fd24dab5d stays in state INITIAL.
java.lang.NullPointerException: Cannot invoke "org.eclipse.dataspaceconnector.policy.model.Policy.getPermissions()" because "policy" is null
	at org.eclipse.dataspaceconnector.ids.transform.ContractOfferToIdsContractOfferTransformer.transform(ContractOfferToIdsContractOfferTransformer.java:63)
	at org.eclipse.dataspaceconnector.ids.transform.ContractOfferToIdsContractOfferTransformer.transform(ContractOfferToIdsContractOfferTransformer.java:36)
	at org.eclipse.dataspaceconnector.ids.core.transform.IdsTransformerRegistryImpl.transform(IdsTransformerRegistryImpl.java:58)
	at org.eclipse.dataspaceconnector.ids.core.transform.IdsTransformerRegistryImpl.transform(IdsTransformerRegistryImpl.java:46)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartContractOfferSender.createContractRequest(MultipartContractOfferSender.java:131)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartContractOfferSender.buildMessagePayload(MultipartContractOfferSender.java:110)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartContractOfferSender.buildMessagePayload(MultipartContractOfferSender.java:44)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.IdsMultipartSender.send(IdsMultipartSender.java:150)
	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartContractOfferSender.send(MultipartContractOfferSender.java:44)
	at org.eclipse.dataspaceconnector.ids.core.message.IdsRemoteMessageDispatcher.send(IdsRemoteMessageDispatcher.java:46)
	at org.eclipse.dataspaceconnector.core.base.RemoteMessageDispatcherRegistryImpl.send(RemoteMessageDispatcherRegistryImpl.java:49)
	at org.eclipse.dataspaceconnector.contract.negotiation.ConsumerContractNegotiationManagerImpl.sendOffer(ConsumerContractNegotiationManagerImpl.java:279)
	at org.eclipse.dataspaceconnector.contract.negotiation.ConsumerContractNegotiationManagerImpl.processRequesting(ConsumerContractNegotiationManagerImpl.java:305)
	at org.eclipse.dataspaceconnector.spi.telemetry.Telemetry.lambda$contextPropagationMiddleware$0(Telemetry.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
	at org.eclipse.dataspaceconnector.common.statemachine.StateProcessorImpl.process(StateProcessorImpl.java:49)
	at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:231)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
	at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:456)
	at org.eclipse.dataspaceconnector.common.statemachine.StateMachine.performLogic(StateMachine.java:118)
	at org.eclipse.dataspaceconnector.common.statemachine.StateMachine.lambda$loop$2(StateMachine.java:106)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected Behavior

- if there is a problem transforming the data, it should not be logged using log level `FINE`
- if there is a problem transforming the data, it should just be logged once and the negotiation should go into some kind of error state
- contract negotiation should work as expected, when the `policyId` field in the DataManagementApi field is used.

### Observed Behavior

- 

## Steps to Reproduce

Example payload to send to the data management API
```json
{
    "connectorId": "foo",
    "connectorAddress": "<connector-address>",
    "offer": {
        "offerId": "<contract-definition-id>:foo",
        "assetId": "<asset-id>",
        "policyId": "<policy-id>"
    }
}
```

## Context Information
-

## Detailed Description
-

## Possible Implementation
-

**Comment by paullatzelsperger** [comment]
looked at this quickly, and just as a heads up: we might have to (temporarily) remove the option to initiate by policy ID again.
