### ISSUE TITLE
ContractNegotiation broken: `SqlContractNegotationStore` persist ContractAgreements without Id

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1270]
# Bug Report

## Describe the Bug

When the `ConsumerContractNegotiationManager` persist a `ContractAgreement` using the `SqlContractNegitationStore` it passes _null_ into the Id Column.
As the Id column is not nullable this causes an exception and nothing is persistent. This behavior results in a connector, that is not able to complete any contract negation.

### Expected Behavior

- Connector does not pass _null_ into the Id column of an contract agreement
- **Exceptions that prevent the connector from persisting contract agreements should not be logged using level INFO!**

### Observed Behavior

The negotiation Id is used as the agreement id.

From `SQlContractNegotationStore`
```java
executeQuery(connection, stmt, negotiation.getId(),
                negotiation.getCorrelationId(),
                negotiation.getCounterPartyId(),
                negotiation.getCounterPartyAddress(),
                negotiation.getType().ordinal(),
                negotiation.getProtocol(),
                negotiation.getState(),
                negotiation.getStateCount(),
                negotiation.getStateTimestamp(),
                negotiation.getErrorDetail(),
                agrId,
                toJson(negotiation.getContractOffers()),
                toJson(negotiation.getTraceContext()));
```

## Steps to Reproduce
1. Start consuming connector with PostgreSQL Extensions
2. Initiate Contract Negotiation

## Context Information

Logs:
```bash
[2022-05-09 15:45:09] [INFO   ] unhandled due to prior sendError
jakarta.servlet.ServletException: org.eclipse.dataspaceconnector.spi.persistence.EdcPersistenceException: ERROR: null value in column "id" of relation "edc_contract_agreement" violates not-null constraint
  Detail: Failing row contains (null, urn:connector:provider, urn:connector:consumer, 1652103909, 1652103909, 1683639909, urn:artifact:1, 28efbbfd-c510-421b-89e0-63cc3772b6b1, null, 1:d5694b52-eeda-440f-8a92-58e3bf53f3e3).
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:508)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1375)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.dataspaceconnector.spi.persistence.EdcPersistenceException: ERROR: null value in column "id" of relation "edc_contract_agreement" violates not-null constraint
  Detail: Failing row contains (null, urn:connector:provider, urn:connector:consumer, 1652103909, 1652103909, 1683639909, urn:artifact:1, 28efbbfd-c510-421b-89e0-63cc3772b6b1, null, 1:d5694b52-eeda-440f-8a92-58e3bf53f3e3).
	at org.eclipse.dataspaceconnector.sql.SqlQueryExecutor.executeQuery(SqlQueryExecutor.java:52)
	at org.eclipse.dataspaceconnector.sql.contractnegotiation.store.SqlContractNegotiationStore.lambda$upsertAgreement$10(SqlContractNegotiationStore.java:270)
	at org.eclipse.dataspaceconnector.transaction.local.LocalTransactionContext.lambda$execute$0(LocalTransactionContext.java:46)
	at org.eclipse.dataspaceconnector.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:63)
	at org.eclipse.dataspaceconnector.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:45)
	at org.eclipse.dataspaceconnector.sql.contractnegotiation.store.SqlContractNegotiationStore.upsertAgreement(SqlContractNegotiationStore.java:263)
	at org.eclipse.dataspaceconnector.sql.contractnegotiation.store.SqlContractNegotiationStore.update(SqlContractNegotiationStore.java:221)
	at org.eclipse.dataspaceconnector.sql.contractnegotiation.store.SqlContractNegotiationStore.lambda$save$3(SqlContractNegotiationStore.java:114)
	at org.eclipse.dataspaceconnector.transaction.local.LocalTransactionContext.lambda$execute$0(LocalTransactionContext.java:46)
	at org.eclipse.dataspaceconnector.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:63)
	at org.eclipse.dataspaceconnector.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:45)
	at org.eclipse.dataspaceconnector.sql.contractnegotiation.store.SqlContractNegotiationStore.save(SqlContractNegotiationStore.java:107)
	at org.eclipse.dataspaceconnector.contract.negotiation.ConsumerContractNegotiationManagerImpl.update(ConsumerContractNegotiationManagerImpl.java:508)
	at org.eclipse.dataspaceconnector.contract.negotiation.ConsumerContractNegotiationManagerImpl.confirmed(ConsumerContractNegotiationManagerImpl.java:219)
	at org.eclipse.dataspaceconnector.ids.api.multipart.handler.ContractAgreementHandler.handleRequest(ContractAgreementHandler.java:110)
	at org.eclipse.dataspaceconnector.ids.api.multipart.controller.MultipartController.request(MultipartController.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 26 more
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "id" of relation "edc_contract_agreement" violates not-null constraint
  Detail: Failing row contains (null, urn:connector:provider, urn:connector:consumer, 1652103909, 1652103909, 1683639909, urn:artifact:1, 28efbbfd-c510-421b-89e0-63cc3772b6b1, null, 1:d5694b52-eeda-440f-8a92-58e3bf53f3e3).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:156)
	at org.eclipse.dataspaceconnector.sql.SqlQueryExecutor.executeQuery(SqlQueryExecutor.java:50)
	... 61 more
```

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
Sorry for the late update. The problem was the renaming of the contract agreement primary key from id to agreement_id, which was not done correctly in our database.  Therefore I will close the issue now.

@ndr-brt Thanks for looking into this with me :)
