### ISSUE TITLE
CosmosPolicyStoreExtension: Unusable because vault is not injectable

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1272]
# Bug Report

## Describe the Bug

The `@Inject` and `@Requires` cannot be used together with the `Vault`. All but the CosmosPolicyStoreExtension resolve the vault by calling `context.getService(Vault.class);` without the usage of any annotations mechanism. As the CosmosPolicyStoreExtension does this different it became unusable.

### Expected Behavior

- `Vault` becomes injectable or
- CosmosPolicyStoreExtension should resolve the vault like all the other extensions

### Observed Behavior

Exception when running a connector with the `CosmosPolicyStoreExtension`

```bash
[2022-05-10 13:32:24] [SEVERE ] Error booting runtime
org.eclipse.dataspaceconnector.spi.EdcException: The following @Require'd features were not provided: [org.eclipse.dataspaceconnector.spi.security.Vault]
	at org.eclipse.dataspaceconnector.boot.system.DependencyGraph.of(DependencyGraph.java:109)
	at org.eclipse.dataspaceconnector.boot.system.ExtensionLoader.loadServiceExtensions(ExtensionLoader.java:142)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:155)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:229)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:89)
	at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:77)

```

## Steps to Reproduce
1. Start connector with CosmosPolicyStoreExtension

## Context Information
This bug is currently blocking some CX Teams from deploying their connector. It would be great if we could get a quick fix on the main branch, for example by having the CosmosPolicyStoreExtension resolving the vault like all the other extensions.

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
Yes, there's already an issue about that: #1237 
In the meantime this fix could remove the `@Inject` for the `Vault`, since at the moment it can't be injected

**Comment by paullatzelsperger** [comment]
@ndr-brt once #1237 is resolved, and assuming we'll make the `Vault` `@Inject`-able, this should resolve "auto-magically", right?
