### ISSUE TITLE
Contract Negotiation of Connector with CosmosDB loops exception

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1281]
# Bug Report

## Describe the Bug

If I run a connector with CosmosDB there is an exception in the loop for the contract negotiation. I would assume the whole negotiation is not working, but have no time to try this out. 

### Expected Behavior

- no exception
- negotiation working

### Observed Behavior

Exception

```bash
[2022-05-11 11:56:10] [SEVERE ] StateMachine [provider-contract-negotiation] error caught
{"ClassName":"RequestTimeoutException","userAgent":"azsdk-java-cosmos/4.28.1 MacOSX/12.3.1 JRE/18","statusCode":408,"resourceAddress":"rntbd://cdb-ms-prod-westus1-fd74.documents.azure.com:14428/apps/287e469d-384e-4682-91f2-2f79143e899c/services/985b7301-3bcc-4e42-a697-5f9b839f7d51/partitions/5b28f359-6963-4be7-a804-aef6396af2c7/replicas/132966942041257131p/","innerErrorMessage":"AsyncRntbdRequestRecord({\"args\":{\"transportRequestId\":39,\"activityId\":\"92f40496-d110-11ec-89f2-efb7d606462b\",\"origin\":\"rntbd://cdb-ms-prod-westus1-fd74.documents.azure.com:14428\",\"replicaPath\":\"/apps/287e469d-384e-4682-91f2-2f79143e899c/services/985b7301-3bcc-4e42-a697-5f9b839f7d51/partitions/5b28f359-6963-4be7-a804-aef6396af2c7/replicas/132966942041257131p\",\"timeCreated\":\"2022-05-11T09:56:05.679794Z\",\"lifetime\":\"PT5.075411293S\"},\"requestLength\":440,\"responseLength\":-1,\"status\":{\"done\":false,\"cancelled\":false,\"completedExceptionally\":false},\"timeline\":[{\"eventName\":\"created\",\"startTimeUTC\":\"2022-05-11T09:56:05.679794Z\",\"durationInMicroSec\":23},{\"eventName\":\"queued\",\"startTimeUTC\":\"2022-05-11T09:56:05.679817Z\",\"durationInMicroSec\":1},{\"eventName\":\"channelAcquisitionStarted\",\"startTimeUTC\":\"2022-05-11T09:56:05.679818Z\",\"durationInMicroSec\":409},{\"eventName\":\"pipelined\",\"startTimeUTC\":\"2022-05-11T09:56:05.680227Z\",\"durationInMicroSec\":389},{\"eventName\":\"transitTime\",\"startTimeUTC\":\"2022-05-11T09:56:05.680616Z\",\"durationInMicroSec\":5074744},{\"eventName\":\"decodeTime\",\"startTimeUTC\":null,\"durationInMicroSec\":0},{\"eventName\":\"received\",\"startTimeUTC\":null,\"durationInMicroSec\":0},{\"eventName\":\"completed\",\"startTimeUTC\":null,\"durationInMicroSec\":0}]})","causeInfo":null,"responseHeaders":"{}","requestHeaders":"[Accept=application/json, x-ms-date=Wed, 11 May 2022 09:56:05 GMT, x-ms-documentdb-collection-rid=2pMvAM0rK+M=, x-ms-client-retry-attempt-count=0, x-ms-documentdb-partitionkey=[\"id\"], x-ms-remaining-time-in-ms-on-client=60000, x-ms-consistency-level=Session, Content-Type=application/json]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.28.1 MacOSX/12.3.1 JRE/18","activityId":"92f40496-d110-11ec-89f2-efb7d606462b","requestLatencyInMs":5078,"requestStartTimeUTC":"2022-05-11T09:56:05.678830Z","requestEndTimeUTC":"2022-05-11T09:56:10.757206Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cdb-ms-prod-westus1-fd74.documents.azure.com:14428/apps/287e469d-384e-4682-91f2-2f79143e899c/services/985b7301-3bcc-4e42-a697-5f9b839f7d51/partitions/5b28f359-6963-4be7-a804-aef6396af2c7/replicas/132966942041257131p/","lsn":0,"globalCommittedLsn":-1,"partitionKeyRangeId":null,"isValid":true,"statusCode":408,"subStatusCode":0,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":0.0,"itemLSN":-1,"sessionToken":null,"backendLatencyInMs":null,"exception":"AsyncRntbdRequestRecord({\"args\":{\"transportRequestId\":39,\"activityId\":\"92f40496-d110-11ec-89f2-efb7d606462b\",\"origin\":\"rntbd://cdb-ms-prod-westus1-fd74.documents.azure.com:14428\",\"replicaPath\":\"/apps/287e469d-384e-4682-91f2-2f79143e899c/services/985b7301-3bcc-4e42-a697-5f9b839f7d51/partitions/5b28f359-6963-4be7-a804-aef6396af2c7/replicas/132966942041257131p\",\"timeCreated\":\"2022-05-11T09:56:05.679794Z\",\"lifetime\":\"PT5.075411293S\"},\"requestLength\":440,\"responseLength\":-1,\"status\":{\"done\":false,\"cancelled\":false,\"completedExceptionally\":false},\"timeline\":[{\"eventName\":\"created\",\"startTimeUTC\":\"2022-05-11T09:56:05.679794Z\",\"durationInMicroSec\":23},{\"eventName\":\"queued\",\"startTimeUTC\":\"2022-05-11T09:56:05.679817Z\",\"durationInMicroSec\":1},{\"eventName\":\"channelAcquisitionStarted\",\"startTimeUTC\":\"2022-05-11T09:56:05.679818Z\",\"durationInMicroSec\":409},{\"eventName\":\"pipelined\",\"startTimeUTC\":\"2022-05-11T09:56:05.680227Z\",\"durationInMicroSec\":389},{\"eventName\":\"transitTime\",\"startTimeUTC\":\"2022-05-11T09:56:05.680616Z\",\"durationInMicroSec\":5074744},{\"eventName\":\"decodeTime\",\"startTimeUTC\":null,\"durationInMicroSec\":0},{\"eventName\":\"received\",\"startTimeUTC\":null,\"durationInMicroSec\":0},{\"eventName\":\"completed\",\"startTimeUTC\":null,\"durationInMicroSec\":0}]})","transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2022-05-11T09:56:05.679794Z","durationInMicroSec":23},{"eventName":"queued","startTimeUTC":"2022-05-11T09:56:05.679817Z","durationInMicroSec":1},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2022-05-11T09:56:05.679818Z","durationInMicroSec":409},{"eventName":"pipelined","startTimeUTC":"2022-05-11T09:56:05.680227Z","durationInMicroSec":389},{"eventName":"transitTime","startTimeUTC":"2022-05-11T09:56:05.680616Z","durationInMicroSec":5076292},{"eventName":"decodeTime","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"received","startTimeUTC":null,"durationInMicroSec":0},{"eventName":"completed","startTimeUTC":"2022-05-11T09:56:10.756908Z","durationInMicroSec":590}],"rntbdRequestLengthInBytes":440,"rntbdResponseLengthInBytes":-1,"requestPayloadLengthInBytes":12,"responsePayloadLengthInBytes":null,"channelTaskQueueSize":1,"pendingRequestsCount":1,"serviceEndpointStatistics":{"availableChannels":2,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2022-05-11T09:56:05.527Z","lastRequestTime":"2022-05-11T09:56:05.336Z","createdTime":"2022-05-11T09:55:47.818206Z","isClosed":false}},"requestResponseTimeUTC":"2022-05-11T09:56:10.757206Z","requestResourceType":"StoredProcedure","requestOperationType":"ExecuteJavaScript"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["west us"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"41493 KB","availableMemory":"4152811 KB","systemCpuLoad":"(2022-05-11T09:55:44.511103Z 7.3%), (2022-05-11T09:55:49.511378Z 13.4%), (2022-05-11T09:55:54.510288Z 6.3%), (2022-05-11T09:55:59.510021Z 6.4%), (2022-05-11T09:56:04.511146Z 7.6%), (2022-05-11T09:56:09.511441Z 8.2%)","availableProcessors":16},"clientCfgs":{"id":1,"machineId":"uuid:1253a3f0-903c-4a32-8b2f-3994656b5dcd","connectionMode":"DIRECT","numberOfClients":5,"connCfg":{"rntbd":"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, nrto:null, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Session, mm: true, prgns: [westus])"}}}
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestRecord.expire(RntbdRequestRecord.java:259)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		at com.azure.cosmos.CosmosScripts.blockStoredProcedureResponse(CosmosScripts.java:271)
		at com.azure.cosmos.CosmosStoredProcedure.execute(CosmosStoredProcedure.java:96)
		at org.eclipse.dataspaceconnector.azure.cosmos.CosmosDbApiImpl.invokeStoredProcedure(CosmosDbApiImpl.java:213)
		at org.eclipse.dataspaceconnector.contract.negotiation.store.CosmosContractNegotiationStore.lambda$nextForState$12(CosmosContractNegotiationStore.java:168)
		at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
		at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
		at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
		at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
		at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
		at org.eclipse.dataspaceconnector.contract.negotiation.store.CosmosContractNegotiationStore.nextForState(CosmosContractNegotiationStore.java:168)
		at org.eclipse.dataspaceconnector.contract.negotiation.ProviderContractNegotiationManagerImpl.lambda$processNegotiationsInState$5(ProviderContractNegotiationManagerImpl.java:254)
		at org.eclipse.dataspaceconnector.common.statemachine.StateProcessorImpl.process(StateProcessorImpl.java:46)
		at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:231)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
		at java.base/java.util.stream.LongPipeline.sum(LongPipeline.java:456)
		at org.eclipse.dataspaceconnector.common.statemachine.StateMachine.performLogic(StateMachine.java:118)
		at org.eclipse.dataspaceconnector.common.statemachine.StateMachine.lambda$loop$2(StateMachine.java:106)
		at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
		at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		... 1 more
```

## Steps to Reproduce
1. Start Connector and wait for exception

## Context Information
-

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by paullatzelsperger** [comment]
couple of questions:
1. was this run against M3 or the current development state of EDC?
1. was Cosmos configured correctly? I.e. were all SPROCs deployed properly?
1. what version of the Cosmos SDK was used?
1. what region and consistency scheme is used in cosmos?
1. what's the expected behaviour for a timed-out request, other than trying again?

When filing bugs, please stick to the template and provide as much context info as possible, otherwise it's difficult for us to assess.

**Comment by DominikPinsel** [comment]
> couple of questions:
> 
> 1. was this run against M3 or the current development state of EDC?

It was running against M3.

> 2. was Cosmos configured correctly? I.e. were all SPROCs deployed properly?

I've missed this. Is there some kind of documentation where I can find the SPROCs?

> 3. what version of the Cosmos SDK was used?
> 4. what region and consistency scheme is used in cosmos?

Region was somewhere in US and consistency scheme was the default one. The CosmosDB is already deleted and I cannot lookup the configuration anymore.

> 5. what's the expected behaviour for a timed-out request, other than trying again?

That's not for me to decide. I was just confused about all the errors in the logs after starting the connector.

**Comment by paullatzelsperger** [comment]
unfortunately it is not (yet) documented anywhere, but we'll make it so that the SPROCs get deployed automatically to get around that problem.
