### ISSUE TITLE
`CosmosContractNegotiationStoreIntegrationTest` are flaky on CI

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1286]
# Bug Report

## Describe the Bug
Looks like `CosmosContractNegotiationStoreIntegrationTest` are flaky:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/verify.yaml?query=branch%3Amain
They work nicely on local with the cosmosdb-emulator.

### Expected Behavior
-

## Steps to Reproduce
-

## Context Information
-

## Detailed Description
```
CosmosContractNegotiationStoreIntegrationTest > findAll_verifySortingInvalidSortField() FAILED
    java.lang.AssertionError: 
    Expecting empty but was: [org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@a1c52ee,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@34134adb,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@5aa70aa0,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@c8eed29c,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@102117bb,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@52084eb5,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@df49dcf1,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@9abdd636,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@e2a10cbf,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@461b629f]
        at org.eclipse.dataspaceconnector.contract.negotiation.store.CosmosContractNegotiationStoreIntegrationTest.findAll_verifySortingInvalidSortField(CosmosContractNegotiationStoreIntegrationTest.java:450)

CosmosContractNegotiationStoreIntegrationTest > queryAgreements_verifySorting_invalidProperty() FAILED
    java.lang.AssertionError: 
    Expecting empty but was: [org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@451424c,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@11271c5e,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@d4d81450,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@b7b298c8,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@4eca5956,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@e405bbe7,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@1ccd13b8,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@a2d5f9c5,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@8a1bc6c0,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@50126f11]
        at org.eclipse.dataspaceconnector.contract.negotiation.store.CosmosContractNegotiationStoreIntegrationTest.queryAgreements_verifySorting_invalidProperty(CosmosContractNegotiationStoreIntegrationTest.java:541)
```

## Possible Implementation
-

**Comment by ndr-brt** [comment]
No more true, there other cosmosdb tests that are still flaky: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6767816614

**Comment by ndr-brt** [comment]
@Izzzu which tests are flaky? the CI seems working flawlessly: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/verify.yaml?query=branch%3Amain
