### ISSUE TITLE
`Upload-Test-Report` CI job fails

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1329]
# Bug Report

## Describe the Bug
The "Test Code" CI workflow failed twice in a row on main branch

### Observed Behavior
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645

## Steps to Reproduce
```console
2022-05-18 07:52:04 +0000 - publish-unit-test-results -  INFO - reading **/test-results/**/*.xml
[20](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645?check_suite_focus=true#step:4:21)22-05-18 07:52:04 +0000 - publish -  INFO - publishing success results for commit 3e4b95654f3fd3d88d2c7f3a2463069271508a5e
2022-05-18 07:52:06 +0000 - publish-unit-test-results - WARNING - Request POST /repos/eclipse-dataspaceconnector/DataSpaceConnector/check-runs failed: Forbidden
20[22](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645?check_suite_focus=true#step:4:23)-05-18 07:52:06 +0000 - publish - WARNING - Request POST /repos/eclipse-dataspaceconnector/DataSpaceConnector/check-runs failed with 403: Forbidden
2022-05-18 07:52:06 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-05-18 07:52:06 +0000 - publish-unit-test-results -  INFO - Response message does not indicate retry-able error
Warning: Request POST /repos/eclipse-dataspaceconnector/DataSpaceConnector/check-runs failed with 403: Forbidden
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 332, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 102, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 98, in publish
    check_run, before_check_run = self.publish_check(stats, cases, conclusion)
  File "/action/publish/publisher.py", line 287, in publish_check
    check_run = self._repo.create_check_run(name=self._settings.check_name,
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 3642, in create_check_run
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/action/publish_unit_test_results.py", line 1[24](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645?check_suite_focus=true#step:4:25), in throttled_gh_request_raw
    return gh_request_raw(cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 1[27](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645?check_suite_focus=true#step:4:28), in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 5[29](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645?check_suite_focus=true#step:4:30), in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 4[40](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6485107645?check_suite_focus=true#step:4:41), in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 866, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/action/publish/retry.py", line 101, in increment
    raise GithubException(response.status, content, response.headers)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

## Context Information
-

## Detailed Description
-

## Possible Implementation
-

**Comment by ndr-brt** [comment]
Opened an issue on the upstream repository: https://github.com/EnricoMi/publish-unit-test-result-action/issues/284
