### ISSUE TITLE
`IdsCatalogApiServiceExtension` requires a metadata store but does not declare it

### ISSUE THREAD

**Issue by oxisto** [eclipse-dataspaceconnector/DataSpaceConnector#138]
# How to reproduce 

Try to start a `IdsCatalogApiServiceExtension` without a metadata store

```
SEVERE 2021-10-09T12:02:52.284687 Error booting runtime
org.eclipse.dataspaceconnector.spi.EdcException: Service not found: org.eclipse.dataspaceconnector.spi.metadata.MetadataStore
        at org.eclipse.dataspaceconnector.system.DefaultServiceExtensionContext.getService(DefaultServiceExtensionContext.java:110)
        at org.eclipse.dataspaceconnector.ids.api.catalog.IdsCatalogApiServiceExtension.registerControllers(IdsCatalogApiServiceExtension.java:71)
        at org.eclipse.dataspaceconnector.ids.api.catalog.IdsCatalogApiServiceExtension.initialize(IdsCatalogApiServiceExtension.java:48)
        at org.eclipse.dataspaceconnector.system.ExtensionLoader.lambda$bootServiceExtensions$0(ExtensionLoader.java:43)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.eclipse.dataspaceconnector.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:43)
        at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:107)
        at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.boot(BaseRuntime.java:64)
```

It seems it should declare that it needs a metadata store such as `:extensions:in-memory:metadata-memory"` (which is actually provided by the basic launcher, but I am creating my own)

Seems it is missing in this function:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/8a5df66d62b430662901dcb102cea5f8b464444f/data-protocols/ids/ids-api-catalog/src/main/java/org/eclipse/dataspaceconnector/ids/api/catalog/IdsCatalogApiServiceExtension.java#L39

I would create a PR but I did not find the appropriate "name" of the extension to put here.

**Comment by ndr-brt** [comment]
`IdsCatalogApiServiceExtension` was removed by #493
