### ISSUE TITLE
Exception in sample 05-transfer-file-cloud: Illegal provider-class name: org.eclipse.dataspaceconnector.azure.blob.core.BlobStoreCoreExtension

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#1445]
### Discussed in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/581

<div type='discussions-op-text'>

<sup>Originally posted by **saudkhan116** January 28, 2022</sup>
Hello,

I am trying to run the sample 05-file-transfer-cloud, the cloud resources have been provisioned successfully and the consumer connector comes up in a ready state, however, the provider is popping up the following exception.

Command to execute:
java -Dedc.fs.config=samples/05-file-transfer-cloud/provider/config.properties -jar samples/05-file-transfer-cloud/provider/build/libs/provider.jar

Logs:
INFO 2022-01-28T16:47:03.2420326 Initialized FS Configuration
DEBUG 2022-01-28T16:47:03.3960308 AzureVaultExtension: general initialization complete
INFO 2022-01-28T16:47:03.3970311 Initialized Azure Vault
INFO 2022-01-28T16:47:03.6892041 AzureVaultExtension: authentication/initialization complete.
Exception in thread "main" java.util.ServiceConfigurationError: org.eclipse.dataspaceconnector.spi.system.ServiceExtension: jar:file:/C:/Users/<USER_PROFILE>/Documents/Workspace/DataSpaceConnector/samples/05-file-transfer-cloud/provider/build/libs/provider.jar!/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension:197: Illegal provider-class name: org.eclipse.dataspaceconnector.azure.blob.core.BlobStoreCoreExtension;
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:599)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parseLine(ServiceLoader.java:1155)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1177)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at org.eclipse.dataspaceconnector.boot.system.ServiceLocatorImpl.loadImplementors(ServiceLocatorImpl.java:30)
        at org.eclipse.dataspaceconnector.boot.system.DefaultServiceExtensionContext.loadExtensions(DefaultServiceExtensionContext.java:170)
        at org.eclipse.dataspaceconnector.boot.system.DefaultServiceExtensionContext.loadServiceExtensions(DefaultServiceExtensionContext.java:160)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:125)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:66)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:44)

Need your advice and suggestions.</div>

**Comment by juliapampus** [comment]
Solved in #582.
