### ISSUE TITLE
Cannot request catalog from connector with 1000+ Assets

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1503]
# Bug Report

## Describe the Bug

When the connector has more than 1000 assets it returns a 503 for catalog requests.

### Expected Behavior

There should not be something like "too many assets to send out contract offers".

### Observed Behavior
-

## Steps to Reproduce
1. Create 1000 Assets with one contract offer per Asset
2. Request Catalog

## Context Information

-

## Detailed Description

-

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by paullatzelsperger** [comment]
Please fill out the bug report properly, in particular information about what database was used, a stacktrace (if available, a 503 suggests that it does), maybe even an exemplary `Asset` plus `DataAddress` as well as the version of the connector.

We will be unable to investigate unless all information is provided.

**Comment by paullatzelsperger** [comment]
Just tried this with two connectors with ca 50000 assets each, using the in-memory store and it worked on current upstream `main`. 

During my testing I have seen 503's when I entered a wrong `providerUrl` - it needs to be `http://<host>:<ids-port>/api/v1/ids/data`, the default `ids-port` is `8282`.

> In my experience a stacktrace in case of a 503 does not happen most of the time.

You can also set `edc.web.rest.error.response.verbose=true` to receive the exception message in the response body.

**Comment by DominikPinsel** [comment]
> Just tried this with two connectors with ca 50000 assets each, using the in-memory store and it worked on current upstream `main`.
> 
> During my testing I have seen 503's when I entered a wrong `providerUrl` - it needs to be `http://<host>:<ids-port>/api/v1/ids/data`, the default `ids-port` is `8282`.
> 
> > In my experience a stacktrace in case of a 503 does not happen most of the time.
> 
> You can also set `edc.web.rest.error.response.verbose=true` to receive the exception message in the response body.
> 
> Could this be an OOM?

Thanks for trying this out. I will reach out to the person that reported the bug to me, and ask to run the test again with an updated log level

**Comment by felipebustillo** [comment]
After updating the log level, this is info the provider control plane returns when a different connector tries to request the catalog:

`	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:508)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1375)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:421)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:377)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$2.run(SelectableChannelEndPoint.java:67)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:366)
	... 6 more
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:493)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:507)
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110)
	... 11 more`

**Comment by paullatzelsperger** [comment]
This looks like the connection gets terminated either because of a size or time limit or both. Not knowing your exact setup (gateways, load balancers, ingresses, firewalls,...) it's hard to make an accurate diagnosis from afar. 

My suggestion to you would be to reproduce this with just two java processes and in-mem stores, then gradually move up to Postgres, then to clusters, etc. to help isolate the problem.

**Comment by felipebustillo** [comment]
> This looks like the connection gets terminated either because of a size or time limit or both. Not knowing your exact setup (gateways, load balancers, ingresses, firewalls,...) it's hard to make an accurate diagnosis from afar.
> 
> My suggestion to you would be to reproduce this with just two java processes and in-mem stores, then gradually move up to Postgres, then to clusters, etc. to help isolate the problem.

Thanks for your answer, Paul. It is also worth mentioning that when we register, say 10 assets on an EDC instance with in-memory stores, when requesting the contract offer we get 20 id's (every assets contains 2 submodels, so this is okay and expected). The request takes 538 ms and returns a 22.57 KB json. On the other hand, when registering the same 10 assets in the PostgreSQL EDC and requesting the catalog, it takes 5.9 s and returns a 448.22 KB file. It basically adds 20x times the contract offers. Is this expected? When more assets are registered, the occurrences of each ID grow exponentially and that's why we get a 503 from a certain number of assets registered.

**Comment by Valentin23** [comment]
We registered all of the test assets (2600 assets) and we can fetch the catalogue with no problems. So, yes, we can close the issue!!

Thanks you very much for your help! @DominikPinsel @paullatzelsperger

**Comment by DrDanielMetz** [comment]
> We registered all of the test assets (2600 assets) and we can fetch the catalogue with no problems. So, yes, we can close the issue!!
> 
> Thanks you very much for your help! @DominikPinsel @paullatzelsperger

And what you are writing now into the criteria of the contract definition?
Can you give an example?

**Comment by Valentin23** [comment]
> > We registered all of the test assets (2600 assets) and we can fetch the catalogue with no problems. So, yes, we can close the issue!!
> > Thanks you very much for your help! @DominikPinsel @paullatzelsperger
> 
> And what you are writing now into the criteria of the contract definition? Can you give an example?

Of course:

`criteria: [{
     "left": "asset:prop:id",
     "op": "=",
     "right": "<asset_id>"
}]`
