### ISSUE TITLE
ContractNegotiationIntegrationTest: race condition

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1505]
# Bug Report

## Describe the Bug

Observed in a non-reproducible manner
```
ContractNegotiationIntegrationTest > testNegotiation_initialOfferAccepted() FAILED
 org.opentest4j.AssertionFailedError:
 expected: null
  but was: org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@e70b6dd7
     at java.base@11.0.15/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     at java.base@11.0.15/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     at java.base@11.0.15/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at app//org.eclipse.dataspaceconnector.contract.negotiation.ContractNegotiationIntegrationTest.testNegotiation_initialOfferAccepted(ContractNegotiationIntegrationTest.java:78
```

## Possible Implementation

Latch waits for the observable to be triggered, then test makes assertion on persisted data.

This is a race condition, since data is persisted after the observable is invoked.

Add post* observable operations?

**Comment by paullatzelsperger** [comment]
Not the biggest fan of `CountDownLatch`es, especially when libs like `awaitility` exists. Maybe wrapping the assertions in await()` will help?
