### ISSUE TITLE
test: fix failure of TransferProcessEventDispatchTest

### ISSUE THREAD

**Issue by iwasakims** [eclipse-dataspaceconnector/DataSpaceConnector#1616]
# Bug Report

## Describe the Bug
3 test cases of TransferProcessEventDispatchTest fail.

### Expected Behavior
The tests pass.

## Steps to Reproduce

```
$ ./gradlew extensions:api:data-management:transferprocess:test
```

## Context Information
_Add any other context about the problem here._

- Used version: main (abc8912ebb54c42bb4e5f67c4e05504c0ef46691)
- OS: Ubuntu 22.04
- JDK: openjdk-11-jdk (11.0.15+10-Ubuntu-0ubuntu0.22.04.1)

## Detailed Description

```
TransferProcessEventDispatchTest > shouldDispatchEventsOnTransferProcessStateChanges(TransferProcessService, EventRouter, RemoteMessageDispatcherRegistry) FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest 
    Wanted but not invoked:
    eventSubscriber.on(
        isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessInitialized)
    );
    -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventsOnTransferProcessStateChanges$0(TransferProcessEventDispatchTest.java:73)
    Actually, there were zero interactions with this mock.
     within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.shouldDispatchEventsOnTransferProcessStateChanges(TransferProcessEventDispatchTest.java:72)

        Caused by:
        Wanted but not invoked:
        eventSubscriber.on(
            isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessInitialized)
        );
        -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventsOnTransferProcessStateChanges$0(TransferProcessEventDispatchTest.java:73)
        Actually, there were zero interactions with this mock.
            at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventsOnTransferProcessStateChanges$0(TransferProcessEventDispatchTest.java:73)

TransferProcessEventDispatchTest > shouldDispatchEventOnTransferProcessFailure(TransferProcessService, EventRouter, RemoteMessageDispatcherRegistry) FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest 
    Wanted but not invoked:
    eventSubscriber.on(
        isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessFailed)
    );
    -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessFailure$3(TransferProcessEventDispatchTest.java:126)
    Actually, there were zero interactions with this mock.
     within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.shouldDispatchEventOnTransferProcessFailure(TransferProcessEventDispatchTest.java:126)

        Caused by:
        Wanted but not invoked:
        eventSubscriber.on(
            isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessFailed)
        );
        -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessFailure$3(TransferProcessEventDispatchTest.java:126)
        Actually, there were zero interactions with this mock.
            at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessFailure$3(TransferProcessEventDispatchTest.java:126)

TransferProcessEventDispatchTest > shouldDispatchEventOnTransferProcessCanceled(TransferProcessService, EventRouter, RemoteMessageDispatcherRegistry) FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest 
    Wanted but not invoked:
    eventSubscriber.on(
        isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessCancelled)
    );
    -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessCanceled$2(TransferProcessEventDispatchTest.java:106)
    Actually, there were zero interactions with this mock.
     within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.shouldDispatchEventOnTransferProcessCanceled(TransferProcessEventDispatchTest.java:106)

        Caused by:
        Wanted but not invoked:
        eventSubscriber.on(
            isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessCancelled)
        );
        -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessCanceled$2(TransferProcessEventDispatchTest.java:106)
        Actually, there were zero interactions with this mock.
            at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessCanceled$2(TransferProcessEventDispatchTest.java:106)
```

## Possible Implementation

* Setting retly.limit to higher values enables transition to expected state.
* Disabling exponential make transition to expected failure state within 10 seconds (which is default timeout of Awaitility).

in TransferProcessEventDispatchTest setUp:

```
        extension.setConfiguration(Map.of("edc.transfer.send.retry.limit", "5",
                                          "edc.transfer.send.retry.base-delay.ms", "0"));
        extension.registerServiceMock(TransferWaitStrategy.class, () -> 1);
```

**Comment by iwasakims** [comment]
The test still fails even with the "Possible Implementation" if the test run with other test cases.

The test passed when I run the test class alone::

```
$ ./gradlew extensions:api:data-management:transferprocess:test  --tests '*TransferProcessEventDispatchTest'
Starting a Gradle Daemon (subsequent builds will be faster)

...

> Task :extensions:api:data-management:transferprocess:test

---------------------------------------------------------------
|  Results: SUCCESS (3 tests, 3 passed, 0 failed, 0 skipped)  |
---------------------------------------------------------------
```

I'm suspecting that using `EdcExtension` has some interference between tests.

**Comment by iwasakims** [comment]
> I'm suspecting that using EdcExtension has some interference between tests.

The cause turned out to be the CompletableFuture does not complete in the test run.
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/abc8912ebb54c42bb4e5f67c4e05504c0ef46691/core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventRouterImpl.java#L45-L52
