### ISSUE TITLE
Local tests fail because `0.0.0.0:8181` is already bound

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1743]
# Bug Report

## Describe the Bug
When running `./gradlew clean test` locally some tests in the Datamanagement API module randomly fail stating that port 8181 is already bound.

### Expected Behavior
All tests should always work.

### Observed Behavior
when [logging STDOUT and STDERR in gradle](https://stackoverflow.com/a/55273517) this stacktrace is logged:
```
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8181
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)
        at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:401)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.eclipse.jetty.server.Server.doStart(Server.java:397)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.dataspaceconnector.extension.jetty.JettyService.start(JettyService.java:98)
        ... 79 more
    Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339)
        ... 94 more

```

## Steps to Reproduce
1. Go to the root directory
2. execute `./gradlew clean test` (`clean` is important to avoid incremental builds)

## Context Information
I assume this does not happen frequently on the GH runners because they're generally slower, so parallelism seems less of a problem here.

- Used version: EDC `main`
- OS: macOS Monterrey 12.5, Arch linux (5.18.x)
- java 18

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
I suspect the problem is when parallel tests instantiate the DataManagementApi: the default context path (NOT the data mgmt API!) is always registered at `<host>:8181/api`, which may cause the binding to fail.

A possible solution could be to supply configuration for the default port as well, and provide randomized values: 
```java
    // from TransferProcessApiControllerIntegrationTest.java:
    @BeforeEach
    void setUp(EdcExtension extension) {
        extension.setConfiguration(Map.of(
                "web.http.port", randomValueHere,
                "web.http.path", "/api"
                "web.http.data.port", String.valueOf(port),
                "web.http.data.path", "/api/v1/data",
                "edc.api.auth.key", authKey
        ));
    }
```

**Comment by jimmarino** [comment]
Having to set this is a bit onerous. How about a range starting at 8181?
