### ISSUE TITLE
`ContractNegotiationIntegrationTest` is flaky

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1868]
# Bug Report

## Describe the Bug
[It failed in an unrelated PR](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/7973148691)

### Expected Behavior
To not fail

### Observed Behavior
```
ContractNegotiationIntegrationTest > testNegotiation_agreementDeclined() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.contract.negotiation.ContractNegotiationIntegrationTest 
    expected: null
     but was: org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@2399e3ec within 15 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
        at app//org.eclipse.dataspaceconnector.contract.negotiation.ContractNegotiationIntegrationTest.testNegotiation_agreementDeclined(ContractNegotiationIntegrationTest.java:173)

        Caused by:
        org.opentest4j.AssertionFailedError: 
        expected: null
         but was: org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@2399e3ec
            at jdk.internal.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
            at java.base@11.0.16/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at app//org.eclipse.dataspaceconnector.contract.negotiation.ContractNegotiationIntegrationTest.lambda$testNegotiation_agreementDeclined$2(ContractNegotiationIntegrationTest.java:184)
```

**Comment by ndr-brt** [comment]
the failure didn't happen again
