### ISSUE TITLE
running the dataspace-connector.jar fails because dataspaceconnector-vault.properties doesnt exit

### ISSUE THREAD

**Issue by maxono1** [eclipse-dataspaceconnector/DataSpaceConnector#2142]
# Bug Report

## Describe the Bug
_after running gradlew.bat :launchers:ids-connector:shadowJar. 
i ran the java -jar launchers/ids-connector/build/libs/dataspace-connector.jar command. but it failed. below is the error code_

### Observed Behavior
WARNING 2022-10-26T17:59:34.5908038 Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring.
INFO 2022-10-26T17:59:34.6258039 Initialized FS Configuration
SEVERE 2022-10-26T17:59:35.0607968 Error booting runtime: Vault file does not exist: dataspaceconnector-vault.properties
org.eclipse.dataspaceconnector.spi.EdcException: Vault file does not exist: dataspaceconnector-vault.properties
        at org.eclipse.dataspaceconnector.core.security.fs.FsVaultExtension.initializeVault(FsVaultExtension.java:73)
        at org.eclipse.dataspaceconnector.core.security.fs.FsVaultExtension.initialize(FsVaultExtension.java:57)
        at org.eclipse.dataspaceconnector.boot.system.injection.lifecycle.InitializePhase.initialize(InitializePhase.java:37)
        at org.eclipse.dataspaceconnector.boot.system.injection.lifecycle.ExtensionLifecycleManager.initialize(ExtensionLifecycleManager.java:61)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.eclipse.dataspaceconnector.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:67)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:152)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:222)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:87)
        at org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:75)

**Comment by ndr-brt** [comment]
Hi, the `ids-connector` launcher has an exhaustive README file that explains how to run it appropriately: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/launchers/ids-connector

**Comment by maxono1** [comment]
i will check it out and see if i can manage, thank you!
