### ISSUE TITLE
Sample 05-file-transfer-cloud broken (assetId)

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#381]
When running sample 05 according to its instructions, the consumer log contains:
```
SEVERE 2021-12-08T10:02:01.741348 Error caught in transfer process manager
java.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(URI.java:3104)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	at org.eclipse.dataspaceconnector.ids.core.message.DataRequestMessageSender.send(DataRequestMessageSender.java:92)
	at org.eclipse.dataspaceconnector.ids.core.message.DataRequestMessageSender.send(DataRequestMessageSender.java:44)
	at org.eclipse.dataspaceconnector.ids.core.message.IdsRemoteMessageDispatcher.send(IdsRemoteMessageDispatcher.java:46)
	at org.eclipse.dataspaceconnector.transfer.core.protocol.provider.RemoteMessageDispatcherRegistryImpl.send(RemoteMessageDispatcherRegistryImpl.java:47)
	at org.eclipse.dataspaceconnector.transfer.core.transfer.TransferProcessManagerImpl.sendOrProcessProvisionedRequests(TransferProcessManagerImpl.java:294)
	at org.eclipse.dataspaceconnector.transfer.core.transfer.TransferProcessManagerImpl.run(TransferProcessManagerImpl.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Presumably the cause is a missing assetId in the query

**Comment by paullatzelsperger** [comment]
quite a bit of work was done in that area and in the samples over the last couple of days. would you mind checking if this still persists?

**Comment by algattik** [comment]
Now this fails with

`java -Dedc.fs.config=samples/05-file-transfer-cloud/provider/config.properties -jar samples/05-file-transfer-cloud/provider/build/libs/provider.jar`

```
SEVERE 2021-12-13T18:02:32.035453 Error booting runtime
org.eclipse.dataspaceconnector.spi.EdcException: Service not found: org.eclipse.dataspaceconnector.common.azure.BlobStoreApi
	at org.eclipse.dataspaceconnector.system.DefaultServiceExtensionContext.getService(DefaultServiceExtensionContext.java:110)
	at org.eclipse.dataspaceconnector.extensions.transfer.CloudTransferExtension.initialize(CloudTransferExtension.java:33)
	at org.eclipse.dataspaceconnector.system.ExtensionLoader.lambda$bootServiceExtensions$0(ExtensionLoader.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.eclipse.dataspaceconnector.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:45)
	at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:107)
	at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.boot(BaseRuntime.java:64)
	at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.main(BaseRuntime.java:41)
INFO 2021-12-13T18:02:32.03907 Shutdown org.eclipse.dataspaceconnector.schema.s3.BucketSchemaExtension@55322aab
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.eclipse.dataspaceconnector.provision.aws.AwsProvisionExtension.shutdown(AwsProvisionExtension.java:98)
	at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.shutdown(BaseRuntime.java:146)
	at org.eclipse.dataspaceconnector.system.runtime.BaseRuntime.lambda$boot$0(BaseRuntime.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by DominikPinsel** [comment]
I will have a look at this
