### ISSUE TITLE
Fix Sample 5: Managed S3 Bucket not provisioned

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#563]
In the README.md the Sample 5 uses an `DataRequest` for a managed AWS S3 Bucket.

JSON snippet from the request:
```json
{
  "dataDestination": {
    "properties": {
      "region": "us-east-1"
    },
    "type": "AmazonS3"
  },
  "managedResources": true,
  "destinationType": "AmazonS3"
}
```

But there is no provisioner registered in the consuming connector and the `TransferProcessManager` throws a `NullPointerException`.

```java
java.lang.NullPointerException
	at org.eclipse.dataspaceconnector.transfer.core.transfer.AsyncTransferProcessManager.checkCompleted(AsyncTransferProcessManager.java:359)
	at org.eclipse.dataspaceconnector.transfer.core.transfer.AsyncTransferProcessManager.run(AsyncTransferProcessManager.java:223)
```

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
PR #576
