### ISSUE TITLE
Java 17

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#649]
At the EDC conf someone asked why we aren't using java 17.
Since it's the newest LTS released and since we've not released something stable yet could be a good moment to upgrade.

From a language perspective, there are some nice new features as `record` classes and improved pattern matching for `switch` case expressions

**Comment by jimmarino** [comment]
+1 to use the build system use Java 17 but I don't think we should use features specific to it.

**Comment by ndr-brt** [comment]
> but I don't think we should use features specific to it.
why?

**Comment by ndr-brt** [comment]
However, I tried to change the build version to 17, launched `/gradlew clean check` but a test failed:
```
IonClientImplTest > submitAnchorRequest() FAILED
    org.eclipse.dataspaceconnector.iam.did.crypto.CryptoException: java.security.InvalidAlgorithmParameterException: Curve not supported: secp256k1 (1.3.132.0.10)
        at app//org.eclipse.dataspaceconnector.iam.did.crypto.key.KeyPairFactory.generateKeyPair(KeyPairFactory.java:52)
        at app//org.eclipse.dataspaceconnector.ion.IonClientImplTest.submitAnchorRequest(IonClientImplTest.java:52)

        Caused by:
        java.security.InvalidAlgorithmParameterException: Curve not supported: secp256k1 (1.3.132.0.10)
            at jdk.crypto.ec/sun.security.ec.ECKeyPairGenerator.ensureCurveIsSupported(ECKeyPairGenerator.java:136)
            at jdk.crypto.ec/sun.security.ec.ECKeyPairGenerator.initialize(ECKeyPairGenerator.java:114)
            at java.base/java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:698)
            at org.eclipse.dataspaceconnector.iam.did.crypto.key.KeyPairFactory.generateKeyPair(KeyPairFactory.java:44)
            ... 1 more
```

Seems like the support for the elliptic curve `secp256k1` was dropped since java 16:
https://bugs.openjdk.java.net/browse/JDK-8251547

@paullatzelsperger do you know what could be a good replacement? (asking you because the `KeyPairFactory` code was written by you)

**Comment by jimmarino** [comment]
> > but I don't think we should use features specific to it.
> 
> why?

Java 11 is LTS and a lot of people use it and we don't need those features.

**Comment by ndr-brt** [comment]
Java 17 is an LTS too, I think record classes could remove a lot of boilerplate code on POJOs.

**Comment by jimmarino** [comment]
> Java 17 is an LTS too, I think record classes could remove a lot of boilerplate code on POJOs.

The problem is a lot of people (i.e. the overwhelming majority of deployments) are still using Java 11 or earlier as a target platform. I think we need to carefully balance a desire to use the latest-and-greatest versus having a runtime that aligns with existing deployment criteria many users have. Also, we should keep in mind Java is on a 6-month release cadence. 

There could be a situation where we absolutely need a feature or don't want to support a legacy version and customers will be forced to upgrade. I don't see Records as warranting that.

**Comment by jimmarino** [comment]
> Ok, but with this mindset also features brought by java 11 (like `var` statement, `Map.of` and so on) could be unsupported by whose are still using java 8 (seems like it's still the most used jdk).
> 
> If there's a rule about LTS (like, use not the last but the last but one) I'm ok with it, we just need to have a clear statement about.

We already made the decision to baseline on Java 11 so we can use those features. The thinking here is that Java 8 is old and nearing non-commercial EOL. For each Java LTS release, I think we should decide based on a variety of inputs, for example, the importance of new features, adoption rate, etc. I'm not sure we need a codified rule for this. 

I don't think we need to wait for Java 11 non-commercial EOL, we just need to see significant Java 17 adoption.

**Comment by paullatzelsperger** [comment]
@ndr-brt about the KeypairFactory
> @paullatzelsperger do you know what could be a good replacement? (asking you because the KeyPairFactory code was written by you

I would even vote to throw the ION implementation out altogether, since ION is not maintained anymore and we never had a feature-complete impl (no anchoring, no type-based search) to begin with.

**Comment by ndr-brt** [comment]
Opened an issue about that.
