### ISSUE TITLE
HealthCheckServiceImplTest unstable

### ISSUE THREAD

**Issue by marcgs** [eclipse-dataspaceconnector/DataSpaceConnector#766]
The `HealthCheckServiceImplTest.isReady_throwsException()` test is flaky. Based on our observations it fails roughly 1% of the time with:

```
HealthCheckServiceImplTest > isReady_throwsException() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.core.health.HealthCheckServiceImplTest
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.core.health.HealthCheckServiceImplTest.isReady_throwsException(HealthCheckServiceImplTest.java:114)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
            at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
            at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
            at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:100)
            ... 5 more
```

**Comment by bscholtes1A** [comment]
@marcgs  is this issue still relevant?

**Comment by marcgs** [comment]
> HealthCheckServiceImplTest

This was back then a flaky test, but it seems now it has been a while since it failed. Closing the story as we have now a [procedure](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#report-on-flaky-tests) in place for dealing with flaky tests.
