### ISSUE TITLE
FileTransferIntegrationTest is flaky

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#848]
# Bug Report

## Describe the Bug
Sometimes the `FileTransferIntegrationTest` fails.

### Expected Behavior
The test should succeed at every build

### Observed Behavior
It happened two times on `main` branch in the last 24 hours:
- https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5449666649
- https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5446900478

with the exception:
```
    java.lang.AssertionError: Gatling Simulation failed
        at org.eclipse.dataspaceconnector.system.tests.utils.GatlingUtils.runGatling(GatlingUtils.java:45)
        at org.eclipse.dataspaceconnector.system.tests.local.FileTransferIntegrationTest.transferFile_success(FileTransferIntegrationTest.java:72)
```

## Steps To Reproduce
not reproducible

## Context Information
-

## Detailed Description
-

## Possible Implementation
-

**Comment by ndr-brt** [comment]
@algattik assigned you since you have worked on this test
